import { Component, OnInit } from '@angular/core';
import {MatDialog} from "@angular/material/dialog";
import {PatientDetailsComponent} from "./patient-details/patient-details.component";

@Component({
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  personsDS = [{
    name: 'Boris Johnson',
    age: 74,
    imageLink: 'https://www.meme-arsenal.com/memes/2fbd653ecba0d0f3caab8a9963589a61.jpg',
    diagnostic: 'Diagnosed with type 2 diabetes.',
    report: {
      "Inclusion": "yes",
      "Gender": "M",
      "Height (m)": 1.63,
      "Mass (kg)": 65.8,
      "BMI": 24.76570439,
      "Race": "White",
      "Ethnicity": "Non-H/L",
      "Group": "Control",
      "group2": "Control",
      "Years of DM": 0,
      "Smoking": "no",
      "Years Smoking": 0,
      "Alcohol": "yes",
      "Hypertension": "no",
      "Duration": 2,
      "Neuropathy": "no",
      "Dizziness": "no",
      "Numbness": "no",
      "Painful feet": "no",
      "Diabetic retinopathy (yes/no)": "no",
      "Retinopathy grade (0-10)": 0,
      "Hx of DM RETINOPATHY": "no",
      "DISTANCE(m)": 786.87,
      "LAPS": 7,
      "SPEED(m/s)": 1.09,
      "eye exam yes/no": "yes",
      "WBC K/uL": 5.1,
      "RBC m/uL": 4.48,
      "Hgb g/dL": 13.4,
      "Hct %": 38.8,
      "MCV fL": 87,
      "MCH pg": 29.9,
      "MCHC %": 34.5,
      "RDW %": 13,
      "Plt Ct K/uL": 212,
      "Glucose mg/dL": 136,
      "Cholest mg/dL": 256,
      "Triglyc mg/dL": 340,
      "HDL mg/dL": 69,
      "CHOL/HD Ratio": 3.7,
      "LDLcalc mg/dL": 119,
      "Creat mg/dL": 78,
      "Albumin mg/dL": 11.5,
      "HbA1c": 5.5,
      "GLUCOSE -HIGH,LOW, NORMAL": "H",
      "CONTROLLED 2": "yes",
      "MEDS": "none",
      "Insulin": "nA",
      "SICAM": 224.083,
      "SVACM": 689.125,
      "CRP": 0.107,
      "CRPmg/L": 1.07,
      "CRP L=<1 M=1-3,H=>3": "M",
      "IL-6": 0,
      "Endothelin 1": 0,
      "Relative CO2 Reactivity MCAR": 1.053089301,
      "Absolute CO2 Reactivity MCAR": 2.436653353,
      "Relative CO2 Reactivity MCAL": 1.202053609,
      "Notes": "BP low",
      "Mahal. Distance outlier test": "Na",
      "MR Baseline": 43.22817273,
      "MR Hypovent": 48.87797035,
      "CO2 Baseline": 43.14285714,
      "CO2 Hypovent": 54.38095238,
      "CO2 Hypervent": 33.0952381,
      "CO2 Baseline 2": 42.9047619,
      "CO2 Hypo - Hyper": 21.28571429,
      "BF diff / CO2 diff": 1.180664805,
      "% BF": 105.8307824,
      "% CO2": 64.31654676,
      "% Reactivity": 1.645467422,
      "IR Global ROI (cm^3)": 1553.896075
    }
  },
    {
      name: 'Gica Elveth',
      age: 68,
      imageLink: 'https://i.imgflip.com/271xx1.jpg',
      diagnostic: 'Diagnosed with type 2 diabetes.',
      report: {
        "Inclusion": "yes",
        "Gender": "F",
        "Height (m)": 1.7,
        "Mass (kg)": 70.3,
        "BMI": 24.32525952,
        "Race": "White",
        "Ethnicity": "Non-H/L",
        "Group": "Control",
        "group2": "Control",
        "Years of DM": 0,
        "Smoking": "no",
        "Years Smoking": 0,
        "Alcohol": "yes",
        "Hypertension": "tes",
        "Duration": 1.2,
        "Neuropathy": "no",
        "Dizziness": "yes",
        "Numbness": "yes",
        "Painful feet": "no",
        "Diabetic retinopathy (yes/no)": "no",
        "Retinopathy grade (0-10)": 0,
        "Hx of DM RETINOPATHY": "no",
        "DISTANCE(m)": 937.77,
        "LAPS": 19,
        "SPEED(m/s)": 1.3,
        "eye exam yes/no": "yes",
        "WBC K/uL": 8.2,
        "RBC m/uL": 4.51,
        "Hgb g/dL": 14.7,
        "Hct %": 43.2,
        "MCV fL": 96,
        "MCH pg": 32.7,
        "MCHC %": 34.1,
        "RDW %": 13.5,
        "Plt Ct K/uL": 264,
        "Glucose mg/dL": 93,
        "Cholest mg/dL": 190,
        "Triglyc mg/dL": 177,
        "HDL mg/dL": 52,
        "CHOL/HD Ratio": 3.7,
        "LDLcalc mg/dL": 103,
        "Creat mg/dL": 124,
        "Albumin mg/dL": 0.1,
        "HbA1c": 5.9,
        "GLUCOSE -HIGH,LOW, NORMAL": "N",
        "CONTROLLED 2": "yes",
        "MEDS": "raloxifene",
        "Insulin": "nA",
        "SICAM": 240.03,
        "SVACM": 1052.936,
        "CRP": 0.575,
        "CRPmg/L": 5.75,
        "CRP L=<1 M=1-3,H=>3": "H",
        "IL-6": 1.545,
        "Endothelin 1": 0,
        "Relative CO2 Reactivity MCAR": 2.153430884,
        "Absolute CO2 Reactivity MCAR": 1.965477632,
        "Relative CO2 Reactivity MCAL": 2.23695938,
        "Notes": "BP high at hypomax",
        "Mahal. Distance outlier test": "",
        "MR Baseline": 33.20771739,
        "MR Hypovent": 37.14445299,
        "CO2 Baseline": 21,
        "CO2 Hypovent": 38,
        "CO2 Hypervent": 12,
        "CO2 Baseline 2": 20,
        "CO2 Hypo - Hyper": 26,
        "BF diff / CO2 diff": 0.809487358,
        "% BF": 130.7426806,
        "% CO2": 216.6666667,
        "% Reactivity": 0.603427757,
        "IR Global ROI (cm^3)": 1473.501849
      }
    },
    {
      name: 'Krakova Iasmin',
      age: 67,
      imageLink: 'https://drkernisan.net/wp-content/uploads/bigstock-Beautiful-Portrait-Of-An-Elder-5884730-e1395250928579.jpg',
      diagnostic: 'Diagnosed with type 2 diabetes.',
      report: {
        "Inclusion": "yes",
        "Gender": "F",
        "Height (m)": 1.83,
        "Mass (kg)": 98,
        "BMI": 29.2633402,
        "Race": "White",
        "Ethnicity": "Non-H/L",
        "Group": "Control",
        "group2": "Control",
        "Years of DM": 0,
        "Smoking": "no",
        "Years Smoking": 0,
        "Alcohol": "no",
        "Hypertension": "yes",
        "Duration": 0,
        "Neuropathy": "no",
        "Dizziness": "no",
        "Numbness": "no",
        "Painful feet": "no",
        "Diabetic retinopathy (yes/no)": "yes",
        "Retinopathy grade (0-10)": 1,
        "Hx of DM RETINOPATHY": "no",
        "DISTANCE(m)": 0,
        "LAPS": 0,
        "SPEED(m/s)": 0,
        "eye exam yes/no": "yes",
        "WBC K/uL": 4.7,
        "RBC m/uL": 5.27,
        "Hgb g/dL": 12.4,
        "Hct %": 37.1,
        "MCV fL": 70,
        "MCH pg": 23.5,
        "MCHC %": 33.3,
        "RDW %": 14.1,
        "Plt Ct K/uL": 246,
        "Glucose mg/dL": 88,
        "Cholest mg/dL": 210,
        "Triglyc mg/dL": 57,
        "HDL mg/dL": 72,
        "CHOL/HD Ratio": 2.9,
        "LDLcalc mg/dL": 127,
        "Creat mg/dL": 110,
        "Albumin mg/dL": 0.3,
        "HbA1c": 7,
        "GLUCOSE -HIGH,LOW, NORMAL": "N",
        "CONTROLLED 2": "no",
        "MEDS": "baby AS",
        "Insulin": "nA",
        "SICAM": 75.418,
        "SVACM": 755.838,
        "CRP": 0.479,
        "CRPmg/L": 4.79,
        "CRP L=<1 M=1-3,H=>3": "H",
        "IL-6": 1.993,
        "Endothelin 1": 0.628,
        "Relative CO2 Reactivity MCAR": 1.536376524,
        "Absolute CO2 Reactivity MCAR": 2.38920406,
        "Relative CO2 Reactivity MCAL": 1.607211305,
        "Notes": "Low sugar levels",
        "Mahal. Distance outlier test": "nA",
        "MR Baseline": "nA",
        "MR Hypovent": "nA",
        "CO2 Baseline": "nA",
        "CO2 Hypovent": "nA",
        "CO2 Hypervent": "nA",
        "CO2 Baseline 2": "nA",
        "CO2 Hypo - Hyper": "nA",
        "BF diff / CO2 diff": "nA",
        "% BF": "nA",
        "% CO2": "nA",
        "% Reactivity": "nA",
        "IR Global ROI (cm^3)": "nA"
      }
    },
    {
      name: 'Eustus Borning',
      age: 67,
      imageLink: 'https://previews.123rf.com/images/dtiberio/dtiberio1802/dtiberio180203067/97265241-insane-bearded-old-person.jpg',
      diagnostic: 'Diagnosed with type 2 diabetes.',
      report: {
        "Inclusion": "yes",
        "Gender": "M",
        "Height (m)": 1.6,
        "Mass (kg)": 49,
        "BMI": 19.140625,
        "Race": "White",
        "Ethnicity": "Non-H/L",
        "Group": "Control",
        "group2": "Control",
        "Years of DM": 0,
        "Smoking": "yes",
        "Years Smoking": 10,
        "Alcohol": "yes",
        "Hypertension": "no",
        "Duration": 3.4,
        "Neuropathy": "no",
        "Dizziness": "no",
        "Numbness": "yes",
        "Painful feet": "no",
        "Diabetic retinopathy (yes/no)": "yes",
        "Retinopathy grade (0-10)": 1,
        "Hx of DM RETINOPATHY": "no",
        "DISTANCE(m)": 688.86,
        "LAPS": 14,
        "SPEED(m/s)": 0.957,
        "eye exam yes/no": "no",
        "WBC K/uL": 5.5,
        "RBC m/uL": 4.15,
        "Hgb g/dL": 12.2,
        "Hct %": 37.4,
        "MCV fL": 90,
        "MCH pg": 29.5,
        "MCHC %": 32.7,
        "RDW %": 13.7,
        "Plt Ct K/uL": 243,
        "Glucose mg/dL": 65,
        "Cholest mg/dL": 205,
        "Triglyc mg/dL": 73,
        "HDL mg/dL": 85,
        "CHOL/HD Ratio": 2.4,
        "LDLcalc mg/dL": 105,
        "Creat mg/dL": 18,
        "Albumin mg/dL": 1.7,
        "HbA1c": 8.1,
        "GLUCOSE -HIGH,LOW, NORMAL": "L",
        "CONTROLLED 2": "no",
        "MEDS": "none",
        "Insulin": "nA",
        "SICAM": 303.568,
        "SVACM": 1209.405,
        "CRP": 0.026,
        "CRPmg/L": 0.26,
        "CRP L=<1 M=1-3,H=>3": "L",
        "IL-6": 0,
        "Endothelin 1": 0,
        "Relative CO2 Reactivity MCAR": -0.848430689,
        "Absolute CO2 Reactivity MCAR": -1.72997655,
        "Relative CO2 Reactivity MCAL": -1.066727105,
        "Notes": "Very High Raar Values",
        "Mahal. Distance outlier test": "",
        "MR Baseline": 69.51470796,
        "MR Hypovent": 78.83948948,
        "CO2 Baseline": 28.0952381,
        "CO2 Hypovent": 37.85714286,
        "CO2 Hypervent": 17.9047619,
        "CO2 Baseline 2": 25.80952381,
        "CO2 Hypo - Hyper": 19.95238095,
        "BF diff / CO2 diff": 0.992881296,
        "% BF": 33.56027994,
        "% CO2": 111.4361702,
        "% Reactivity": 0.301161462,
        "IR Global ROI (cm^3)": "nA"
      }
    },
    {
      name: 'Justus Joseph',
      age: 69,
      imageLink: 'https://www.theleidencollection.com/wp-content/uploads/2018/03/GD-107-Gerrit-Dou-Old-Man-Praying-768x1073.jpg',
      diagnostic: 'Diagnosed with type 2 diabetes.',
      report: {
        "Inclusion": "yes",
        "Gender": "M",
        "Height (m)": 1.7,
        "Mass (kg)": 68,
        "BMI": 23.52941176,
        "Race": "White",
        "Ethnicity": "Non-H/L",
        "Group": "Control",
        "group2": "Control",
        "Years of DM": 0,
        "Smoking": "no",
        "Years Smoking": 0,
        "Alcohol": "no",
        "Hypertension": "yes",
        "Duration": 0,
        "Neuropathy": "no",
        "Dizziness": "no",
        "Numbness": "no",
        "Painful feet": "no",
        "Diabetic retinopathy (yes/no)": "yes",
        "Retinopathy grade (0-10)": 2,
        "Hx of DM RETINOPATHY": "no",
        "DISTANCE(m)": 719.01,
        "LAPS": 6,
        "SPEED(m/s)": 0.999,
        "eye exam yes/no": "no",
        "WBC K/uL": 5.6,
        "RBC m/uL": 4.33,
        "Hgb g/dL": 14.5,
        "Hct %": 40.4,
        "MCV fL": 93,
        "MCH pg": 33.4,
        "MCHC %": 35.9,
        "RDW %": 12.9,
        "Plt Ct K/uL": 222,
        "Glucose mg/dL": 75,
        "Cholest mg/dL": 219,
        "Triglyc mg/dL": 122,
        "HDL mg/dL": 47,
        "CHOL/HD Ratio": 4.7,
        "LDLcalc mg/dL": 148,
        "Creat mg/dL": 126,
        "Albumin mg/dL": 1,
        "HbA1c": 2.2,
        "GLUCOSE -HIGH,LOW, NORMAL": "N",
        "CONTROLLED 2": "no",
        "MEDS": "lovastatin",
        "Insulin": "nA",
        "SICAM": 251.667,
        "SVACM": 729.006,
        "CRP": 0.12,
        "CRPmg/L": 1.2,
        "CRP L=<1 M=1-3,H=>3": "M",
        "IL-6": 0,
        "Endothelin 1": 0,
        "Relative CO2 Reactivity MCAR": 2.035549181,
        "Absolute CO2 Reactivity MCAR": 3.59619802,
        "Relative CO2 Reactivity MCAL": 2.329988441,
        "Notes": "Chymerism active",
        "Mahal. Distance outlier test": "nA",
        "MR Baseline": "nA",
        "MR Hypovent": "nA",
        "CO2 Baseline": "nA",
        "CO2 Hypovent": "nA",
        "CO2 Hypervent": "nA",
        "CO2 Baseline 2": "nA",
        "CO2 Hypo - Hyper": "nA",
        "BF diff / CO2 diff": "nA",
        "% BF": "nA",
        "% CO2": "nA",
        "% Reactivity": "nA",
        "IR Global ROI (cm^3)": 1625.802211
      }
    },
    {
      name: 'Mathilda Johnsonin',
      age: 70,
      imageLink: 'https://www.demilked.com/magazine/wp-content/uploads/2018/05/5b0d102872024-old-women-transformation-pin-up-models-dollhouse-photography-1-5b0be7547e953__700.jpg',
      diagnostic: 'Diagnosed with type 2 diabetes.',
      report: {
        "Inclusion": "yes",
        "Gender": "F",
        "Height (m)": 1.7,
        "Mass (kg)": 68,
        "BMI": 23.52941176,
        "Race": "White",
        "Ethnicity": "Non-H/L",
        "Group": "Control",
        "group2": "Control",
        "Years of DM": 0,
        "Smoking": "no",
        "Years Smoking": 0,
        "Alcohol": "no",
        "Hypertension": "yes",
        "Duration": 0,
        "Neuropathy": "no",
        "Dizziness": "no",
        "Numbness": "no",
        "Painful feet": "no",
        "Diabetic retinopathy (yes/no)": "yes",
        "Retinopathy grade (0-10)": 2,
        "Hx of DM RETINOPATHY": "no",
        "DISTANCE(m)": 719.01,
        "LAPS": 6,
        "SPEED(m/s)": 0.999,
        "eye exam yes/no": "no",
        "WBC K/uL": 5.6,
        "RBC m/uL": 4.33,
        "Hgb g/dL": 14.5,
        "Hct %": 40.4,
        "MCV fL": 93,
        "MCH pg": 33.4,
        "MCHC %": 35.9,
        "RDW %": 12.9,
        "Plt Ct K/uL": 222,
        "Glucose mg/dL": 75,
        "Cholest mg/dL": 219,
        "Triglyc mg/dL": 122,
        "HDL mg/dL": 47,
        "CHOL/HD Ratio": 4.7,
        "LDLcalc mg/dL": 148,
        "Creat mg/dL": 126,
        "Albumin mg/dL": 1,
        "HbA1c": 2.2,
        "GLUCOSE -HIGH,LOW, NORMAL": "N",
        "CONTROLLED 2": "no",
        "MEDS": "lovastatin",
        "Insulin": "nA",
        "SICAM": 251.667,
        "SVACM": 729.006,
        "CRP": 0.12,
        "CRPmg/L": 1.2,
        "CRP L=<1 M=1-3,H=>3": "M",
        "IL-6": 0,
        "Endothelin 1": 0,
        "Relative CO2 Reactivity MCAR": 2.035549181,
        "Absolute CO2 Reactivity MCAR": 3.59619802,
        "Relative CO2 Reactivity MCAL": 2.329988441,
        "Notes": "Chymerism active",
        "Mahal. Distance outlier test": "nA",
        "MR Baseline": "nA",
        "MR Hypovent": "nA",
        "CO2 Baseline": "nA",
        "CO2 Hypovent": "nA",
        "CO2 Hypervent": "nA",
        "CO2 Baseline 2": "nA",
        "CO2 Hypo - Hyper": "nA",
        "BF diff / CO2 diff": "nA",
        "% BF": "nA",
        "% CO2": "nA",
        "% Reactivity": "nA",
        "IR Global ROI (cm^3)": 1625.802211
      }
    }];

  constructor(public dialog: MatDialog) { }

  ngOnInit() {
  }

  moreDetails(data) {
    const dialogRef = this.dialog.open(PatientDetailsComponent, {
      width: (window.innerWidth < 760 ? '100%' : '40%'), data
    });
  }
}
